services:
  api:
    command: [ "uvicorn", "--port", "8000", "--host", "0.0.0.0", "src.api:app" ]

  server:
    build:
      dockerfile: dockerfiles/services/server/Dockerfile.prod
      context: .
    volumes:
      - ./dockerfiles/services/server/nginx.conf.prod:/etc/nginx/extends/prod.conf
