services:
  api:
    build:
      dockerfile: dockerfiles/services/api/Dockerfile.prod
      context: .
    command: [ "uvicorn", "--port", "8000", "--host", "0.0.0.0", "src.api:app" ]

  server:
    build:
      dockerfile: dockerfiles/services/server/Dockerfile.prod
      context: .
